/**
 * groups.data.ts  (M2 - Willer Pegasus, partage avec M1 Leonel)
 * ---------------------------------------------------------------
 * Donnees fictives des groupes de repetition.
 * Correspond a : src/components/groupes/groups.data.ts
 *
 * [BACKEND] A remplacer par : GET /api/groups?featured=true
 */

import type { TutoringGroup } from '../../types'

export const FEATURED_GROUPS: TutoringGroup[] = [
  {
    id: 'g1',
    name: 'Groupe La Reussite',
    emoji: '🏆',
    adminName: 'M. Kamga Eric',
    adminId: 'tutor-kamga',
    subjects: ['Mathematiques', 'Physique-Chimie'],
    levels: ['Terminale C', 'Terminale D'],
    location: 'Centre Dschang',
    maxStudents: 8,
    currentStudents: 6,
    pricePerHour: 1500,
    rating: 4.9,
    reviewCount: 43,
    description: 'Groupe intensif de preparation au BAC C/D. Methode rigoureuse, exercices corriges chaque semaine.',
    verified: true,
  },
  {
    id: 'g2',
    name: 'Les Geeks',
    emoji: '💻',
    adminName: 'M. Tagne Junior',
    adminId: 'tutor-tagne',
    subjects: ['Informatique'],
    levels: ['2nde', '1ere', 'Terminale'],
    location: 'Quartier Foto',
    maxStudents: 6,
    currentStudents: 4,
    pricePerHour: 1800,
    rating: 4.8,
    reviewCount: 28,
    description: 'Initiation a la programmation Python, Web et algorithmique. Projets pratiques en equipe.',
    verified: true,
  },
  {
    id: 'g3',
    name: 'Les Intellos',
    emoji: '📚',
    adminName: 'Mme Tchana Sylvie',
    adminId: 'tutor-tchana',
    subjects: ['Francais', 'Philosophie', 'Histoire-Geo'],
    levels: ['1ere', 'Terminale A'],
    location: 'Ngui Dschang',
    maxStudents: 10,
    currentStudents: 8,
    pricePerHour: 1200,
    rating: 4.7,
    reviewCount: 35,
    description: 'Groupe litteraire pour le BAC A. Dissertation, analyse de texte et culture generale.',
    verified: true,
  },
  {
    id: 'g4',
    name: 'Genius Academy',
    emoji: '🧪',
    adminName: 'Mme Mbouh Carine',
    adminId: 'tutor-mbouh',
    subjects: ['SVT', 'Physique-Chimie'],
    levels: ['3eme', '2nde', '1ere D'],
    location: 'Tsinkop',
    maxStudents: 8,
    currentStudents: 5,
    pricePerHour: 1400,
    rating: 4.6,
    reviewCount: 21,
    description: 'Sciences de la vie et physique pour le BEPC et le BAC D. Nombreux TD et exercices types.',
    verified: false,
  },
  {
    id: 'g5',
    name: 'English Masters',
    emoji: '🌍',
    adminName: 'Mlle Fotso Aline',
    adminId: 'tutor-fotso',
    subjects: ['Anglais'],
    levels: ['Primaire', 'College', 'Lycee'],
    location: 'Centre Dschang',
    maxStudents: 6,
    currentStudents: 6,
    pricePerHour: 1600,
    rating: 4.9,
    reviewCount: 52,
    description: 'Groupe de conversation et grammaire anglaise. Methode immersive, tous niveaux acceptes.',
    verified: true,
  },
  {
    id: 'g6',
    name: 'Top Maths',
    emoji: '📐',
    adminName: 'M. Nana Bertrand',
    adminId: 'tutor-nana',
    subjects: ['Mathematiques'],
    levels: ['6eme', '5eme', '4eme', '3eme'],
    location: 'Foto',
    maxStudents: 10,
    currentStudents: 7,
    pricePerHour: 1000,
    rating: 4.7,
    reviewCount: 19,
    description: 'Soutien en mathematiques pour le college. Bases solides, exercices progressifs.',
    verified: true,
  },
]
